### ISSUE TITLE
两头水的音调

### ISSUE THREAD

**Issue by Guanchishan** [siuze/sy_ngy__LJ#10]
![image](https://user-images.githubusercontent.com/30859354/129438370-16a65bc3-9cd4-4f25-b744-3ea4982d1df3.png)
![image](https://user-images.githubusercontent.com/30859354/129438374-bf36f1b1-8f38-4169-826d-2bacbee577ae.png)
写进zingzeu word的音调待确认
@siuze 你可以读下这个词，telegram发我音频吗？

**Comment by siuze** [comment]
县志这本记得变调和我处不同，我处如今声调为33 33 33，音频稍后发送

**Comment by Guanchishan** [comment]
原书拼音等榕拼 连江ver. 出了再说，先按叶伟口音记录了zingzeu word。close
