### ISSUE TITLE
[縣誌] 表示瓢的ciek5是否蠘

### ISSUE THREAD

**Issue by Guanchishan** [siuze/sy_ngy__LJ#12]
![image](https://user-images.githubusercontent.com/30859354/129439500-f99a9a07-d1f1-43e4-9f10-9e9e94a88c17.png)

**Comment by siuze** [comment]
向家中长辈求证，他们表示两字发音不同，上图表示勺子的cieh韵尾当是h，相关音频已发送至电报

**Comment by Guanchishan** [comment]
那表示勺子的本字当是什么呢？

**Comment by Guanchishan** [comment]
<img width="512" alt="企业微信截图_16290408436412" src="https://user-images.githubusercontent.com/30859354/129484513-278139f5-3f8e-4122-9da4-be3307997e07.png">
榕注没给ciah/cieh5配汉字，但是有收录此词。
@ZySieng 以下词汇，你认为汉字如何处理好？训读为勺字？还是找个相近的同音字？还是造一个填音节的汉字？
糞□	puŋ44 ts‘iaʔ5 （ #17 ）
鐵□	t‘ie12 ts‘ieʔ5
漏□	lau44 ts‘ieʔ5

**Comment by Guanchishan** [comment]
[训读为勺字](https://github.com/ztl8702/zingzeu-data/commit/932f17a6b17c66656116909898bb47e0b6f1459b)，结案
