### ISSUE TITLE
崗字讀音問題

### ISSUE THREAD

**Issue by Guanchishan** [siuze/sy_ngy__LJ#13]
表示山峰的sang53 ngoung213，縣誌寫爲山崗。
@siuze 崗在連江有去聲一讀嗎？

**Comment by siuze** [comment]
询问得知有的，我处亦可不类化，说sang55（或53） goung213（釭韵），sang55 goung21 goung213

**Comment by Guanchishan** [comment]
sang55 goung21 goung213 已加入contrib
山崗 已加入 zingzeu word
