### ISSUE TITLE
[縣誌] “bung55 ciah5”底“ciah5”是什麼字

### ISSUE THREAD

**Issue by Guanchishan** [siuze/sy_ngy__LJ#17]
<html>
<body>

粪□ | 糞□ | puŋ44 ts‘iaʔ5 | bung55 ciah5 | 粪勺
-- | -- | -- | -- | --

</body>
</html>

**Comment by siuze** [comment]
我处说bung44 cieh5，长辈表示后字和表示勺子的cieh5 cieh5 一样

**Comment by Guanchishan** [comment]
好像上回你有在榕典群问这个ciak/ciek写法，然后江姐建议写为勺是吗？

**Comment by siuze** [comment]
是的

**Comment by Guanchishan** [comment]
修齐君对是否采用  勺这个字  如何看？

顺便抄送 @zysieng 看看有没啥意见

**Comment by ZySieng** [comment]
我目前没有什么看法，市区不说这个词，不是很熟。勺的音韵地位合不上，但是可以暂时把它当成训读字

**Comment by Guanchishan** [comment]
那写清楚榕典注的同时可以先用勺这个字

**Comment by Guanchishan** [comment]
[相关数据已入库](https://github.com/ztl8702/zingzeu-data/commit/932f17a6b17c66656116909898bb47e0b6f1459b)，结案
