### ISSUE TITLE
le21 ji24 ma33的le21 ji24是什么字？

### ISSUE THREAD

**Issue by Guanchishan** [siuze/sy_ngy__LJ#24]
<html>
<body>

□□妈 | □□媽 | le21 ʒi24 ma33 | le21 ji24 ma33 | 招魂女人 | 人品 | 1304 | L
-- | -- | -- | -- | -- | -- | -- | --

</body>
</html>

**Comment by siuze** [comment]
![image](https://user-images.githubusercontent.com/54578647/129479638-925a50ac-409d-450d-9114-42e22eb3e198.png)
《連江漁村..》如此記。
我原認為首字可能是禮。

**Comment by Guanchishan** [comment]
榕典目前采取现有文献优先的原则，先做奶子妈
