### ISSUE TITLE
bo21 u24 ne33的bo21 u24是什么字？

### ISSUE THREAD

**Issue by Guanchishan** [siuze/sy_ngy__LJ#25]
<html>
<body>

宝□奶 | 寶□奶 | pɔ21 u24 nε33 | bo21 u24 ne33 | 接生婆 | 人品 | 1304 | L
-- | -- | -- | -- | -- | -- | -- | --

</body>
</html>

**Comment by siuze** [comment]
![image](https://user-images.githubusercontent.com/54578647/129479129-61df850f-06f3-4f2b-8a4e-9b2e99f46a76.png)
《連江漁村...》中記如此，我處說ba21 u24 ne33，當是音變，參考藍尾星-》loung21 mui21 ling55

**Comment by Guanchishan** [comment]
先按渔村写法。先close
