### ISSUE TITLE
拋糞斗	p‘a21 puŋ24 nau33

### ISSUE THREAD

**Issue by Guanchishan** [siuze/sy_ngy__LJ#30]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | 抛*粪斗 | 拋糞斗 | p‘a21 puŋ24 nau33 | pa21 bung24 nau33 | 打滚翻 | 文教 | 1309 | R |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

</body>

</html>

@siuze 有说这个词吗？你认为本字或单字音调是？

糞斗二字不知道能不能读成bung24 no33

**Comment by siuze** [comment]
有說的，該詞寫法應該沒問題，我們這裡說pa33 wung55 nau33，沒有別的讀音。
畚斗/糞斗我們這裡說bung55 nau33，不說bung no。
倒糞倒do33 bung55 no213(注意聲調)是倒垃圾，“糞斗囝掏去到”的意思，用的不多，一般說倒糞斗。

**Comment by Guanchishan** [comment]
笔误了 想问的糞斗是bung nau 我这里也不说no 
ok

**Comment by Guanchishan** [comment]
糞斗囝是糞斗的小称，还是代指垃圾？

**Comment by siuze** [comment]
> 糞斗囝是糞斗的小称，还是代指垃圾？

指糞斗

**Comment by Guanchishan** [comment]
拋糞斗一詞已記入zing zeu word。close
