### ISSUE TITLE
姑媽一詞讀音

### ISSUE THREAD

**Issue by Guanchishan** [siuze/sy_ngy__LJ#4]
![image](https://user-images.githubusercontent.com/30859354/106248823-80a0f200-624c-11eb-8d47-3ed2036975ba.png)
 
“姑妈	ku44 ma44	姑母	%后字声调当为33”

@siuze 你意思是姑妈讀爲gu55 ma33嗎？telegram發個語音？

**Comment by Guanchishan** [comment]
然後這個十七、农事：
饲*牛	tsi44 ŋu52	看牛	%原书即为ts

@siuze 汝意思是講應該是ts'i ngu伓是？有無聽過儂講tsi ngu？

**Comment by siuze** [comment]
> ![image](https://user-images.githubusercontent.com/30859354/106248823-80a0f200-624c-11eb-8d47-3ed2036975ba.png)
> 
> “姑妈 ku44 ma44 姑母 %后字声调当为33”
> 
> @siuze 你意思是姑妈讀爲gu55 ma33嗎？telegram發個語音？

这个地方应该是我看错了，父亲的姑姑我们这里是说gu55 ma33，原文ku44 ma44 应该说的是姑姑’（父亲的姐妹），因为这种表达我们这里没有使用，我误以为原书打错发音了。

**Comment by siuze** [comment]
> 然後這個十七、农事：
> 饲*牛 tsi44 ŋu52 看牛 %原书即为ts
> 
> @siuze 汝意思是講應該是ts'i ngu伓是？有無聽過儂講tsi ngu？

这个表达我们这里没有使用（我们这里用觑牛）。原书发音不送气，和一般时候【饲】的发音有所差异，我不知道是印错了还是发音确实如此，就暂留疑问，补注是为了说明这里不是校对时候的疏漏。
