### ISSUE TITLE
拍在連江有不送氣的讀法嗎

### ISSUE THREAD

**Issue by Guanchishan** [siuze/sy_ngy__LJ#5]
2107 | 拍* | 拍 | paʔ12 | bah24 | 打 |   | 动作 | 1310 | R |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

查縣誌原文確實沒送氣。拍在連江有不送氣的讀法嗎？

**Comment by siuze** [comment]
> 
> 
> 2107 | 拍* | 拍 | paʔ12 | bah24 | 打 |   | 动作 | 1310 | R |   |  
> 
> -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
> 
> 
> 
> 
> 
> 查縣誌原文確實沒送氣。拍在連江有不送氣的讀法嗎？

未曾用过，当是送气符号脱漏
