### ISSUE TITLE
suok5 loy55 ung55=俥螺風？

### ISSUE THREAD

**Issue by Guanchishan** [siuze/sy_ngy__LJ#9]
![image](https://user-images.githubusercontent.com/30859354/129437906-5ea173ef-4bb4-4760-887a-9b3b6a1b1908.png)
![image](https://user-images.githubusercontent.com/30859354/129437909-93a65c89-7bf0-4f73-ab1b-929dc8095799.png)

**Comment by Guanchishan** [comment]
suok5在當地也有旋轉的意思嗎？

**Comment by siuze** [comment]
家中长辈表示并不了解该词，suo53有旋转之意，详见：https://m.weibo.cn/status/4390030597990415?

**Comment by Guanchishan** [comment]
已反馈给子善等进一步处理

**Comment by Guanchishan** [comment]
视为不同词，加入zingzeu word
